# Generated by Django 2.2.7 on 2020-08-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_qty', models.IntegerField()),
                ('prod_price', models.FloatField()),
                ('prod_price_qty', models.FloatField()),
                ('active', models.CharField(default='Y', max_length=50)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'db_table': 'Price_info',
            },
        ),
    ]
